name: BetterSpades

on:
  #push:
  #  tags:
  #    - '*'
  - push

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Resolve dependencies
        run: sudo apt-get install libopenal-dev libopengl-dev libglew-dev libglfw3-dev libdeflate-dev libenet-dev

      - name: Install cglm
        run: |
          git clone https://github.com/recp/cglm
          mkdir cglm/build
          cd cglm/build
          cmake ..
          make
          sudo make install
          cd ../..

      - name: Compile
        run: make binary

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Linux binary release
          path: build/betterspades

  macos-build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Resolve dependencies
        run: brew install mesa-glu glew glfw enet libdeflate cglm coreutils

      - name: Compile
        run: |
          make binary

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: macOS binary release
          path: |
            build/betterspades

  windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            git
            base-devel
            tree
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-openal
            mingw-w64-x86_64-glew
            mingw-w64-x86_64-glfw
            mingw-w64-x86_64-enet
            mingw-w64-x86_64-libdeflate
            mingw-w64-x86_64-cglm

      - name: Compile
        run: |
          make binary

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Windows binary release
          path: |
            build/betterspades.exe
