name: BetterSpades

on:
  - pull_request
  - push

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Resolve dependencies
        run: sudo apt-get install libopenal-dev libopengl-dev libglew-dev libglfw3-dev libdeflate-dev libenet-dev

      - name: Install cglm
        run: |
          git clone https://github.com/recp/cglm
          mkdir cglm/build
          cd cglm/build
          cmake ..
          make
          sudo make install
          cd ../..

      - name: Compile
        run: make binary

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Linux binary release
          path: build/betterspades

  macos-build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Resolve dependencies
        run: brew install mesa-glu glew glfw enet libdeflate cglm coreutils

      - name: Compile
        run: |
          make binary
          echo "::set-env name=LIBCGLM::$(greadlink -f /usr/local/opt/cglm/lib/libcglm.0.dylib)"
          echo "::set-env name=LIBGLFW::$(greadlink -f /usr/local/opt/glfw/lib/libglfw.3.dylib)"
          echo "::set-env name=LIBGLEW::$(greadlink -f /usr/local/opt/glew/lib/libGLEW.2.2.dylib)"
          echo "::set-env name=LIBGLU::$(greadlink -f /usr/local/opt/mesa-glu/lib/libGLU.1.dylib)"
          echo "::set-env name=LIBGL::$(greadlink -f /usr/local/opt/mesa/lib/libGL.1.dylib)"
          echo "::set-env name=LIBENET::$(greadlink -f /usr/local/opt/enet/lib/libenet.7.dylib)"
          echo "::set-env name=LIBDEFLATE::$(greadlink -f /usr/local/opt/libdeflate/lib/libdeflate.0.dylib)"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: macOS binary release
          path: |
            build/betterspades
            ${{ env.LIBCGLM }}
            ${{ env.LIBGLFW }}
            ${{ env.LIBGLEW }}
            ${{ env.LIBGLU }}
            ${{ env.LIBGL }}
            ${{ env.LIBENET }}
            ${{ env.LIBDEFLATE }}
